# Generated by Django 6.0.7 on 2026-08-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marks',
            options={'verbose_name': 'Mark', 'verbose_name_plural': 'Marks'},
        ),
    ]
